### PR TITLE
Allow integration of subplugins.

### PR DESCRIPTION
**Pull request by juacas**
This PR enables offlinequiz to use new subplugins without changing the core plugin.
It implements:
* A new member function add_to_tabs to offlinequiz_default_report
* A new attribute to tabs structure to allow the subplugins to set their "title".
* A poll across the subplugins to allow them to register in the tabs structure.

This PR is tested and running well with a custom report-subplugin.

This feature is very important because teh community would need to implement subplugins for this activity and currently they are imposible to integrate.

I hope this will be useful and be integrated in current 4.1 and next 4.2 versions.

### CODE REVIEW

**Comment by LisaE14** [comment]
Guten Tag,

ich bin bis einschließlich 22. April 2024 nicht im Büro.
In dringenden Fällen wenden Sie sich bitte an meine Kolleg*innen unter der DW 1111 oder per E-Mail an ***@***.***

Mit freundlichen Grüßen
Lisa Eckerstorfer

>>> univietw ***@***.***> 04/19/24 14:43 >>>

Closed #219.

-- 
Reply to this email directly or view it on GitHub:
https://github.com/academic-moodle-cooperation/moodle-mod_offlinequiz/pull/219#event-12538262609

**Comment by univietw** [comment]
Hi @juacas,
Since we changed a lot in our branches I didn't bother to rebase your pull request. But I cherry-picked your commit to our master. It's going to be available with the upcoming 4.4 version.
Thanks for your work.
One question: Do yo want to share your report plugin you are programming? If it might interest other users we could integrate it into offlinequiz too.
Best regards

**Comment by juacas** [comment]
One last question, do you plan to backport this into 401_STABLE, 402_STABLE and 403_STABLE?

**Comment by univietw** [comment]
Hi, first a thanks for the plugin, I will have a look at it some time later. 
for 4.4 there might be some incompabilities for your plugin, since we plan on supporting wildcards for the ID-Number pre-/postfix. I will push new things immediately once I'm finished developing something, if you want I can keep you up to date about it and I'm happy for your suggestions for changes if needed.
If you want us to get your plugin into offlinequiz-core I am happy to talk about that too, it sounds like a really nice feature.

I plan to have more subplugin types, but first I would need to have a good codebase to support that. I am working on that. At the moment I'm working on getting rid of the parts written more than 15 years ago. The new correction algorithm already has this in mind, so it is possible and I want to encourage that. Give me some years, it'll become better. We have many things planned (optical character recognition, open questions, letter format, ....), but not enough time. So I am happy for any pull requests. 

About your request: I backported all your pull requests to 4.1, 4.2 and 4.3.

**Comment by juacas** [comment]
Hi,
I would be happy to take steps to integrate the "offlinequiz_identified" plugin into the core.
As an example, my implementation uses a horrendous hack that would be better solved with an elegant refactoring of the response form. I needed to split the PDF generation in two stages: header/footer and body to do a loop.

However, I am not sure if it is better to integrate it into the codebase and tie the subplugin lifecycle to the main plugin. For example, the "offlinequiz_identified" subplugin currently supports MOODLE_401_STABLE, MOODLE_402_STABLE, MOODLE_403_STABLE versions without having to do maintenance or backports.

Let's talk about that.

**Pull request closed without merging**
