### PR TITLE
Add questions instructions version 2

### PR DESCRIPTION
**Pull request by rezeau**
Please consider this new version of my previous PR.
* add extra option "Answer prompt" to "Print info about answers" Form settings
* depending on question type "Select one:" or "Select one or more:" will be printed between the question text and the list of answers
* the various "info about answers" are now also printed on the "Preview for forms" page, to make it more similar to the actual printed questions form

### CODE REVIEW

**Comment by goggo24** [comment]
Thanks for providing the pull request! I will close the other pull request #101. Our developer is the next month on holiday, but afterwards we will take a look and prove it. Cheers, Eva

**Comment by rezeau** [comment]
Thanks @goggo24

**Comment by rezeau** [comment]
Any progress on this issue?

**Comment by goggo24** [comment]
Currently we did not have time to take a look at your pull request. Unfortunately, our developer is not fulltime with us and currently busy with other urgent matters. We will let you know, as soon as we find time to prove it.

**Comment by mwreichel** [comment]
is already implemented for some years

**Pull request closed without merging**
