### PR TITLE
Print questions instructions (single/multiple answers expected)

### PR DESCRIPTION
**Pull request by rezeau**
Signed-off-by: rezeau <joseph@rezeau.org>

### CODE REVIEW

**Comment by rezeau** [comment]
Further to this discussion on the French Moodle forum I suggest adding instructions for each question, so that student knows what kind of answer is expected: single or multiple. This is necessary because, unlike the online quiz, the offline quiz displays the same kind of boxes for both types. i.e. no "radio buttons"

**Comment by goggo24** [comment]
Hey Joseph, thanks for your pull request, but we won't take it, because the setting already exists ;) 
Under **Form settings** of an offline test you'll find _print info about answers_.  
With this option you can control, which additional information about the question is printed on the question sheet. You can choose between: 
- Nothing (default)
- Question type - Depending on question type Single-Choice, Multiple-Choice, All-or-Nothing Multiple-Choice will be printed
- Number of correct answers - The number of correct answers will be printed
We hope, that this solution works for you too! Eva
print_answer_setting

**Comment by goggo24** [comment]
Hey, I just reopened the pull request, because it's easier to write here than in the french forum ;)
I could imagine your "style" as a 4th opportunity for our _print info about answers_, but you have to support more than only the multiple-choice questiontyp, for example All-or-Nothing. I have no idea, how you distinguish the text, but if you provide a pull request in this direction, we will have a look and prove the integration! At the moment we ourselves are happy with the 3 settings and they satisfy our needs. Salutations de Vienne, Eva

**Comment by rezeau** [comment]
Thanks for re-opening this PR, Eva. I will try to re-work my PR to use your _print info about answers_ menu. Just to make sure, would it be _a new PR_, OR _the current one amended_?

**Comment by goggo24** [comment]
@rezeau thanks for the new pull request #103

**Pull request closed without merging**
